### ISSUE TITLE
History flooder

### ISSUE THREAD

**Issue by Githubman6996** [DannyDan0167/Blooket-Cheats#2]
Can I get the individual code for the script

**Comment by DannyDan0167** [comment]
here:

var num=prompt("History flood amount:");done=false;x=window.location.href;for (var i=1; i<=num; i++){history.pushState(0, 0, i==num?x:i.toString());if(i==num){done=true}}if(done===true){alert("History flood successful! "+window.location.href+" now appears in your history "+num+(num==1?" time.":" times."))}

**Comment by Githubman6996** [comment]
Thanks

**Comment by Githubman6996** [comment]
Also what's history flood even do
